language: python
python:
- '3.6'
dist: trusty
sudo: false
services:
  - redis-server
  - docker
cache:
  directories:
  - "$HOME/.cache/pip"
install:
  - pip install .[dev]
  - pip install codecov
script:
  - python setup.py test
after_success:
  - codecov
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" "$HEROKU_REGISTRY_URL";
    docker push m1yag1/mikefromit;
    fi

