language: python
python:
- '3.6'
dist: trusty
sudo: required
services:
  - redis-server
  - docker
install:
  - docker build -t heroku/mikefromit .
  - docker run -d --name redis redis:latest
  - docker run -d -p 5000:5000 --link redis:redis heroku/mikefromit
  - docker ps
  - docker run --link redis:redis m1yag1/mikefromit /bin/sh -c "cd /app; pip3 install .[dev]; python setup.py test"
script:
  - python setup.py test
after_success:
  - codecov
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" "$HEROKU_REGISTRY_URL";
    docker push m1yag1/mikefromit;
    fi

