dist: trusty
sudo: false
services:
  - redis-server
  - docker
script:
  - python setup.py test
after_success:
  - codecov
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" "$HEROKU_REGISTRY_URL";
    docker push mike.arb/mikefromit;
    fi

