language: python
python:
  - '3.6'
dist: trusty
sudo: required
services:
  - redis-server
  - docker
install:
  - docker-compose -f travis-compose.yml up -d
script:
  - docker exec mikefromit_website_1 /bin/bash -c "cd /app;python setup.py test"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" "$HEROKU_REGISTRY_URL";
    docker push "$HEROKU_REGISTRY_URL"/mikefromit;
    fi
