language: python
python:
  - '3.6'
dist: trusty
sudo: required
services:
  - redis-server
  - docker
before_install:
before_install:
  # Remove the PostgreSQL installed by Travis
  - sudo apt-get purge pgdg-keyring '^postgresql.*' -y
  - sudo apt-get autoremove -y -qq
  - sudo rm -rf /etc/postgresql
  - sudo rm -rf /var/lib/postgresql
  - sudo rm -f /etc/apt/sources.list.d/pgdg-source.list
install:
  - docker-compose -f travis-compose.yml up -d
script:
  - docker exec mikefromit_website_1 /bin/bash -c "cd /app;python setup.py test"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" "$HEROKU_REGISTRY_URL";
    docker push "$HEROKU_REGISTRY_URL"/mikefromit;
    fi
