version: '3'
services:
  web:
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - DB_HOST=db
      - DB_NAME=mikefromit
    command: flask run --host=0.0.0.0 --port=5000
    links:
      - db
      - redis
  db:
    image: postgres:9.6-alpine
    ports:
      - '127.0.0.1:5433:5432'
  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6380:6380'
