version: '3'
services:
  web:
    context: .
    dockerfile: Dockerfile-travis
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    links:
      - db
      - redis
  db:
    image: postgres:9.6-alpine
    environment:
      - DB_NAME=testing
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6380:6380'
